version: 0.2
phases:
  install:
    commands:
      - echo "Welcome to Technical Cloud Knowledge"
      - sudo apt update -y
      - sudo apt install httpd -y
  build:
    commands:
     - echo Build started on `date`
     - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuration NGINX
